#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/python:2.7.14
#    steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run: |
#             sudo docker -v
#             sudo docker build -t hello-world .



version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      #- run: docker build -t $ECR_REPO:0.1 .
      - run: docker build -t hello-world .
      - run: docker run -p 80:80 hello-world
